name: Electric potential energy of a charge configuration
id: potential_energy_charge_configuration
topic: electric_potential
difficulty: 8
equation: energy eq coulomb_constant mul (charge mul charge ) frac (2 mul length )
symbol_overrides:
- energy: ''
- charge: q_1
- charge: q_2
- length: r
name_overrides:
- energy: Potential [energy]
- charge: ''
- charge: ''
- length: Separation
